name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build App

    runs-on: ubuntu-latest
    
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build distZip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sudoku_solver_app.zip
          path: app\build\distributions\app.zip
